/**
 * Picture cards for Gala mode. `he` is fully vocalized (she reads Hebrew with nikud),
 * `en` feeds the AI brief, `emoji` is the picture. Style cards carry a Suno style prompt.
 */
export const STEPS = [
  { id: 'who',   q: 'מִי בַּשִּׁיר?',        emoji: '🧑‍🎤' },
  { id: 'world', q: 'מֵאֵיזֶה עוֹלָם?',      emoji: '📺', optional: true },
  { id: 'where', q: 'אֵיפֹה זֶה קוֹרֶה?',    emoji: '🗺️' },
  { id: 'what',  q: 'מָה קוֹרֶה?',           emoji: '⚡' },
  { id: 'mood',  q: 'אֵיךְ מַרְגִּישִׁים?',   emoji: '💗' },
  { id: 'style', q: 'אֵיזֶה סִגְנוֹן?',      emoji: '🎵' },
];

export const CARDS = {
  who: [
    { id: 'me',       emoji: '🙋‍♀️', he: 'אֲנִי',              en: 'me (a 7-year-old girl)' },
    { id: 'princess', emoji: '👸',   he: 'נְסִיכָה',            en: 'a princess' },
    { id: 'prince',   emoji: '🤴',   he: 'נָסִיךְ',             en: 'a prince' },
    { id: 'queen',    emoji: '👑',   he: 'מַלְכָּה',            en: 'a queen' },
    { id: 'unicorn',  emoji: '🦄',   he: 'חַד־קֶרֶן',           en: 'a unicorn' },
    { id: 'dog',      emoji: '🐶',   he: 'כֶּלֶב',              en: 'a dog' },
    { id: 'puppy',    emoji: '🐕',   he: 'גּוּר כְּלָבִים',     en: 'a puppy' },
    { id: 'cat',      emoji: '🐱',   he: 'חָתוּל',              en: 'a cat' },
    { id: 'kitten',   emoji: '🐈',   he: 'חֲתַלְתּוּל',         en: 'a kitten' },
    { id: 'dragon',   emoji: '🐉',   he: 'דְּרָקוֹן',           en: 'a dragon' },
    { id: 'dino',     emoji: '🦖',   he: 'דִּינוֹזָאוּר',       en: 'a dinosaur' },
    { id: 'robot',    emoji: '🤖',   he: 'רוֹבּוֹט',            en: 'a robot' },
    { id: 'fairy',    emoji: '🧚',   he: 'פֵיָה',               en: 'a fairy' },
    { id: 'mermaid',  emoji: '🧜‍♀️', he: 'בַּת־יָם',            en: 'a mermaid' },
    { id: 'family',   emoji: '👨‍👩‍👧', he: 'אַבָּא וְאִמָּא',   en: 'mom and dad' },
    { id: 'dad',      emoji: '👨',   he: 'אַבָּא',              en: 'dad' },
    { id: 'mom',      emoji: '👩',   he: 'אִמָּא',              en: 'mom' },
    { id: 'grandma',  emoji: '👵',   he: 'סַבְתָּא',            en: 'grandma' },
    { id: 'grandpa',  emoji: '👴',   he: 'סַבָּא',              en: 'grandpa' },
    { id: 'sibling',  emoji: '👧👦', he: 'אָח אוֹ אָחוֹת',      en: 'a brother or sister' },
    { id: 'baby',     emoji: '👶',   he: 'תִּינוֹק',            en: 'a baby' },
    { id: 'friends',  emoji: '👭',   he: 'חֲבֵרוֹת',            en: 'best friends' },
    { id: 'teacher',  emoji: '👩‍🏫', he: 'הַמּוֹרָה',           en: 'my teacher' },
    { id: 'monster',  emoji: '👾',   he: 'מִפְלֶצֶת חֲמוּדָה',  en: 'a cute little monster' },
    { id: 'ghost',    emoji: '👻',   he: 'רוּחַ רְפָאִים',      en: 'a friendly ghost' },
    { id: 'bunny',    emoji: '🐰',   he: 'אַרְנָב',             en: 'a bunny' },
    { id: 'bear',     emoji: '🧸',   he: 'דֻּבִּי',              en: 'a teddy bear' },
    { id: 'lion',     emoji: '🦁',   he: 'אַרְיֵה',             en: 'a lion' },
    { id: 'elephant', emoji: '🐘',   he: 'פִּיל',               en: 'an elephant' },
    { id: 'monkey',   emoji: '🐵',   he: 'קוֹף',                en: 'a monkey' },
    { id: 'giraffe',  emoji: '🦒',   he: 'גִ׳ירָפָה',           en: 'a giraffe' },
    { id: 'panda',    emoji: '🐼',   he: 'פַּנְדָּה',           en: 'a panda' },
    { id: 'penguin',  emoji: '🐧',   he: 'פִּינְגְּוִין',       en: 'a penguin' },
    { id: 'owl',      emoji: '🦉',   he: 'יַנְשׁוּף',           en: 'an owl' },
    { id: 'butterfly',emoji: '🦋',   he: 'פַּרְפַּר',           en: 'a butterfly' },
    { id: 'bee',      emoji: '🐝',   he: 'דְּבוֹרָה',           en: 'a bee' },
    { id: 'fish',     emoji: '🐠',   he: 'דָּג',                en: 'a little fish' },
    { id: 'dolphin',  emoji: '🐬',   he: 'דּוֹלְפִין',          en: 'a dolphin' },
    { id: 'horse',    emoji: '🐴',   he: 'סוּס',                en: 'a horse' },
    { id: 'frog',     emoji: '🐸',   he: 'צְפַרְדֵּעַ',         en: 'a frog' },
    { id: 'turtle',   emoji: '🐢',   he: 'צָב',                 en: 'a turtle' },
    { id: 'astro',    emoji: '👩‍🚀', he: 'אַסְטְרוֹנָאוּטִית',  en: 'a girl astronaut' },
    { id: 'super',    emoji: '🦸‍♀️', he: 'גִּבּוֹרַת־עָל',      en: 'a superhero girl' },
    { id: 'pirate',   emoji: '🏴‍☠️', he: 'פִּירָטִית',          en: 'a pirate girl' },
    { id: 'witch',    emoji: '🧙‍♀️', he: 'מְכַשֵּׁפָה טוֹבָה',  en: 'a good witch' },
    { id: 'wizard',   emoji: '🧙',   he: 'קוֹסֵם',              en: 'a wizard' },
    { id: 'alien',    emoji: '👽',   he: 'חַיְזָר',             en: 'a friendly alien' },
    { id: 'snowman',  emoji: '⛄',   he: 'אִישׁ שֶׁלֶג',        en: 'a snowman' },
    { id: 'doll',     emoji: '🪆',   he: 'בֻּבָּה',             en: 'a doll that comes alive' },
    { id: 'clown',    emoji: '🤡',   he: 'לֵיצָן',              en: 'a clown' },
    { id: 'chef',     emoji: '👩‍🍳', he: 'טַבָּחִית',           en: 'a chef' },
    { id: 'doctor',   emoji: '👩‍⚕️', he: 'רוֹפְאָה',            en: 'a doctor' },
    { id: 'police',   emoji: '👮‍♀️', he: 'שׁוֹטֶרֶת',           en: 'a police officer' },
    { id: 'firefighter', emoji: '👩‍🚒', he: 'כַּבָּאִית',       en: 'a firefighter' },
    { id: 'ballerina',emoji: '🩰',   he: 'רַקְדָנִית',          en: 'a ballerina' },
    { id: 'singer',   emoji: '🎤',   he: 'זַמֶּרֶת',            en: 'a singer' },
    { id: 'car',      emoji: '🚗',   he: 'מְכוֹנִית מְדַבֶּרֶת', en: 'a talking car' },
    { id: 'sun',      emoji: '☀️',   he: 'הַשֶּׁמֶשׁ',          en: 'the sun' },
    { id: 'moon',     emoji: '🌙',   he: 'הַיָּרֵחַ',           en: 'the moon' },
    { id: 'star',     emoji: '⭐',   he: 'כּוֹכָב קָטָן',       en: 'a little star' },
    { id: 'cloud',    emoji: '☁️',   he: 'עָנָן',               en: 'a cloud' },
    { id: 'flower',   emoji: '🌸',   he: 'פֶּרַח',              en: 'a flower' },
    { id: 'tree',     emoji: '🌳',   he: 'עֵץ',                 en: 'an old tree' },
    { id: 'icecream', emoji: '🍦',   he: 'גְּלִידָה',           en: 'an ice cream' },
    { id: 'cake',     emoji: '🧁',   he: 'קַאפְּקֵייק',         en: 'a cupcake' },
  ],
  world: [
    { id: 'none',      emoji: '🌈', he: 'הָעוֹלָם שֶׁלִּי',        en: '' },
    { id: 'bluey',     emoji: '🐶', he: 'בְּלוּאִי',              en: 'Bluey (Bluey, Bingo, Bandit and Chilli, family games and make-believe)' },
    { id: 'gabby',     emoji: '🏠', he: 'גַּבִּי בֵּית הַבֻּבּוֹת', en: "Gabby's Dollhouse (Gabby, Pandy Paws, Cakey, the cat-tastic dollhouse)" },
    { id: 'peppa',     emoji: '🐷', he: 'פֶּפָּה פִּיג',           en: 'Peppa Pig (Peppa, George, muddy puddles)' },
    { id: 'pawpatrol', emoji: '🚒', he: 'מִפְרַץ הַהַרְפַּתְקָאוֹת', en: 'PAW Patrol (Chase, Skye, Marshall, rescue pups)' },
    { id: 'frozen',    emoji: '❄️', he: 'לְשַׁבֵּר אֶת הַקֶּרַח',  en: 'Frozen (Elsa, Anna, Olaf, ice magic)' },
    { id: 'moana',     emoji: '🌊', he: 'מוֹאָנָה',               en: 'Moana (the ocean, Maui, sailing)' },
    { id: 'encanto',   emoji: '🦋', he: 'אֶנְקַנְטוֹ',             en: 'Encanto (Mirabel, the magical family house)' },
    { id: 'tangled',   emoji: '👱‍♀️', he: 'רַפּוּנְזֶל',          en: 'Tangled (Rapunzel, the long hair, floating lanterns)' },
    { id: 'ariel',     emoji: '🧜‍♀️', he: 'בַּת הַיָּם הַקְּטַנָּה', en: 'The Little Mermaid (Ariel, under the sea)' },
    { id: 'cinderella',emoji: '👠', he: 'סִינְדֶּרֶלָה',           en: 'Cinderella (the glass slipper, the ball at midnight)' },
    { id: 'snowwhite', emoji: '🍎', he: 'שִׁלְגִּיָּה',            en: 'Snow White and the seven dwarfs' },
    { id: 'belle',     emoji: '🌹', he: 'הַיָּפָה וְהַחַיָּה',     en: 'Beauty and the Beast (Belle, the enchanted castle)' },
    { id: 'jasmine',   emoji: '🧞', he: 'אַלַדִּין',               en: 'Aladdin (Jasmine, the genie, the magic carpet)' },
    { id: 'lionking',  emoji: '🦁', he: 'מֶלֶךְ הָאֲרָיוֹת',       en: 'The Lion King (Simba, Timon and Pumbaa)' },
    { id: 'toystory',  emoji: '🤠', he: 'צַעֲצוּעַ שֶׁל סִפּוּר',  en: 'Toy Story (Woody, Buzz, toys that come alive)' },
    { id: 'cars',      emoji: '🏎️', he: 'מְכוֹנִיּוֹת',           en: 'Cars (Lightning McQueen, racing)' },
    { id: 'nemo',      emoji: '🐠', he: 'מוֹצְאִים אֶת נֶמוֹ',     en: 'Finding Nemo (Nemo, Dory, the reef)' },
    { id: 'insideout', emoji: '😊', he: 'הַקּוֹל בָּרֹאשׁ',        en: 'Inside Out (Joy, Sadness, the emotions inside the head)' },
    { id: 'stitch',    emoji: '👾', he: 'לִילוֹ וְסְטִיץ׳',       en: 'Lilo and Stitch (ohana, Hawaii)' },
    { id: 'zootopia',  emoji: '🐰', he: 'זוּטְרוֹפּוֹלִיס',        en: 'Zootopia (Judy Hopps, Nick, the animal city)' },
    { id: 'minions',   emoji: '🍌', he: 'מִינְיוֹנִים',            en: 'Minions (bananas, silly gibberish)' },
    { id: 'sonic',     emoji: '💨', he: 'סוֹנִיק',                 en: 'Sonic the Hedgehog (super speed, golden rings)' },
    { id: 'mario',     emoji: '🍄', he: 'סוּפֶּר מַרְיוֹ',         en: 'Super Mario (mushrooms, coins, jumping)' },
    { id: 'pokemon',   emoji: '⚡', he: 'פּוֹקִימוֹן',             en: 'Pokémon (Pikachu, catching pokémon)' },
    { id: 'roblox',    emoji: '🎮', he: 'רוֹבְּלוֹקְס',            en: 'Roblox (blocky avatars, games inside games)' },
    { id: 'minecraft', emoji: '⛏️', he: 'מַיְנְקְרַאפְט',          en: 'Minecraft (building with blocks, creepers, diamonds)' },
    { id: 'barbie',    emoji: '💖', he: 'בַּרְבִּי',               en: 'Barbie (pink dreamhouse)' },
    { id: 'lol',       emoji: '🎀', he: 'בֻּבּוֹת LOL',            en: 'L.O.L. Surprise dolls' },
    { id: 'pony',      emoji: '🦄', he: 'הַפּוֹנִי הַקָּטָן שֶׁלִּי', en: 'My Little Pony (friendship is magic)' },
    { id: 'kitty',     emoji: '🐱', he: 'הֵלוֹ קִיטִי',            en: 'Hello Kitty' },
    { id: 'ladybug',   emoji: '🐞', he: 'מִירָקוּלוּס',            en: 'Miraculous Ladybug (Ladybug and Cat Noir, Paris)' },
    { id: 'spidey',    emoji: '🕷️', he: 'סְפַּיְדִי',              en: 'Spidey and his Amazing Friends' },
    { id: 'masha',     emoji: '🐻', he: 'מָאשָׁה וְהַדֹּב',         en: 'Masha and the Bear' },
    { id: 'sofia',     emoji: '👸', he: 'הַנְּסִיכָה סוֹפְיָה',    en: 'Sofia the First' },
    { id: 'elena',     emoji: '👑', he: 'אֶלֶנָה מֵאָבָלוֹר',       en: 'Elena of Avalor' },
    { id: 'wish',      emoji: '⭐', he: 'מִשְׁאָלָה',              en: 'Wish (Asha and the wishing star)' },
    { id: 'raya',      emoji: '🐉', he: 'רָאיָה וְהַדְּרָקוֹן',    en: 'Raya and the Last Dragon' },
    { id: 'tiana',     emoji: '🐸', he: 'הַנְּסִיכָה וְהַצְּפַרְדֵּעַ', en: 'The Princess and the Frog (Tiana, New Orleans)' },
    { id: 'mulan',     emoji: '⚔️', he: 'מוּלָאן',                 en: 'Mulan' },
    { id: 'babyshark', emoji: '🦈', he: 'בֵּיְבִּי שַׁארְק',       en: 'Baby Shark' },
    { id: 'cocomelon', emoji: '🍉', he: 'קוֹקוֹמֶלוֹן',            en: 'Cocomelon (JJ and the nursery rhymes)' },
    { id: 'numberblocks', emoji: '🔢', he: 'נַמְבֶּרְבְּלוֹקְס',   en: 'Numberblocks' },
    { id: 'yuval',     emoji: '🎈', he: 'יוּבָל הַמְבֻלְבָּל',     en: 'Yuval Hamevulbal (Israeli kids show, silly and musical)' },
    { id: 'keves',     emoji: '🐑', he: 'הַכֶּבֶשׂ הַשִּׁשָּׁה־עָשָׂר', en: 'HaKeves HaShisha Asar (classic Israeli children songs)' },
    { id: 'pijama',    emoji: '🛌', he: 'פִּיגָ׳מָה',             en: 'Pijama (Israeli kids series)' },
    { id: 'hopi',      emoji: '📺', he: 'הוֹפּ!',                  en: 'Hop! channel songs and games' },
  ],
  where: [
    { id: 'home',    emoji: '🏠', he: 'בַּבַּיִת',           en: 'at home' },
    { id: 'room',    emoji: '🛏️', he: 'בַּחֶדֶר שֶׁלִּי',   en: 'in my room' },
    { id: 'kitchen', emoji: '🍳', he: 'בַּמִּטְבָּח',        en: 'in the kitchen' },
    { id: 'garden',  emoji: '🌷', he: 'בַּגִּנָּה',          en: 'in the garden' },
    { id: 'beach',   emoji: '🏖️', he: 'בַּיָּם',             en: 'at the beach' },
    { id: 'pool',    emoji: '🏊‍♀️', he: 'בַּבְּרֵכָה',         en: 'at the swimming pool' },
    { id: 'sea',     emoji: '🐠', he: 'מִתַּחַת לַמַּיִם',   en: 'under the sea' },
    { id: 'space',   emoji: '🚀', he: 'בֶּחָלָל',            en: 'in outer space' },
    { id: 'moon',    emoji: '🌕', he: 'עַל הַיָּרֵחַ',       en: 'on the moon' },
    { id: 'clouds',  emoji: '☁️', he: 'עַל עָנָן',           en: 'on a cloud' },
    { id: 'rainbow', emoji: '🌈', he: 'עַל הַקֶּשֶׁת',       en: 'on a rainbow' },
    { id: 'forest',  emoji: '🌳', he: 'בַּיַּעַר',           en: 'in a forest' },
    { id: 'jungle',  emoji: '🌴', he: 'בַּגּ׳וּנְגֶּל',      en: 'in the jungle' },
    { id: 'mountain',emoji: '⛰️', he: 'עַל הָהָר',           en: 'on a mountain' },
    { id: 'desert',  emoji: '🏜️', he: 'בַּמִּדְבָּר',        en: 'in the desert' },
    { id: 'snow',    emoji: '❄️', he: 'בַּשֶּׁלֶג',           en: 'in the snow' },
    { id: 'island',  emoji: '🏝️', he: 'בְּאִי בּוֹדֵד',      en: 'on a desert island' },
    { id: 'castle',  emoji: '🏰', he: 'בְּטִירָה',           en: 'in a castle' },
    { id: 'school',  emoji: '🏫', he: 'בְּבֵית הַסֵּפֶר',    en: 'at school' },
    { id: 'kinder',  emoji: '🎨', he: 'בַּגַּן',              en: 'at kindergarten' },
    { id: 'park',    emoji: '🎡', he: 'בְּלוּנָה פַּארְק',   en: 'at an amusement park' },
    { id: 'playground', emoji: '🛝', he: 'בַּגַּן שַׁעֲשׁוּעִים', en: 'at the playground' },
    { id: 'zoo',     emoji: '🦁', he: 'בְּגַן חַיּוֹת',      en: 'at the zoo' },
    { id: 'farm',    emoji: '🐄', he: 'בַּחַוָּה',            en: 'on a farm' },
    { id: 'circus',  emoji: '🎪', he: 'בַּקִּרְקָס',          en: 'at the circus' },
    { id: 'candy',   emoji: '🍭', he: 'בְּאֶרֶץ הַמַּמְתַּקִּים', en: 'in candy land' },
    { id: 'toyland', emoji: '🧸', he: 'בְּאֶרֶץ הַצַּעֲצוּעִים', en: 'in toy land' },
    { id: 'dream',   emoji: '💭', he: 'בְּתוֹךְ חֲלוֹם',     en: 'inside a dream' },
    { id: 'night',   emoji: '🌙', he: 'בַּלַּיְלָה',         en: 'at night under the stars' },
    { id: 'rainday', emoji: '☔', he: 'בְּיוֹם גָּשׁוּם',     en: 'on a rainy day' },
    { id: 'city',    emoji: '🏙️', he: 'בָּעִיר הַגְּדוֹלָה', en: 'in the big city' },
    { id: 'street',  emoji: '🛣️', he: 'בָּרְחוֹב שֶׁלָּנוּ', en: 'on our street' },
    { id: 'car',     emoji: '🚗', he: 'בַּמְּכוֹנִית',       en: 'in the car' },
    { id: 'train',   emoji: '🚂', he: 'בָּרַכֶּבֶת',         en: 'on a train' },
    { id: 'plane',   emoji: '✈️', he: 'בַּמָּטוֹס',          en: 'on an airplane' },
    { id: 'ship',    emoji: '🚢', he: 'בָּאֳנִיָּה',          en: 'on a ship' },
    { id: 'balloon', emoji: '🎈', he: 'בְּכַדּוּר פּוֹרֵחַ', en: 'in a hot-air balloon' },
    { id: 'market',  emoji: '🛒', he: 'בַּשּׁוּק',            en: 'at the market' },
    { id: 'bakery',  emoji: '🥐', he: 'בַּמַּאֲפִיָּה',       en: 'at the bakery' },
    { id: 'hospital',emoji: '🏥', he: 'בְּבֵית חוֹלִים',     en: 'at the hospital' },
    { id: 'grandmas',emoji: '🏡', he: 'אֵצֶל סַבְתָּא',       en: "at grandma's house" },
    { id: 'wedding', emoji: '💒', he: 'בַּחֲתֻנָּה',          en: 'at a wedding' },
    { id: 'shabbat', emoji: '🕯️', he: 'בְּשֻׁלְחַן שַׁבָּת', en: 'at the Shabbat table' },
    { id: 'jerusalem', emoji: '🕌', he: 'בִּירוּשָׁלַיִם',   en: 'in Jerusalem' },
    { id: 'telaviv', emoji: '🌆', he: 'בְּתֵל אָבִיב',       en: 'in Tel Aviv' },
    { id: 'kinneret',emoji: '🌊', he: 'בַּכִּנֶּרֶת',        en: 'at the Sea of Galilee' },
    { id: 'volcano', emoji: '🌋', he: 'לְיַד הַר גַּעַשׁ',   en: 'next to a volcano' },
    { id: 'cave',    emoji: '🕳️', he: 'בִּמְעָרָה',          en: 'in a cave' },
    { id: 'treehouse', emoji: '🪵', he: 'בְּבַיִת עַל עֵץ',   en: 'in a treehouse' },
    { id: 'lab',     emoji: '🧪', he: 'בְּמַעְבָּדָה',        en: 'in a science lab' },
  ],
  what: [
    { id: 'party',   emoji: '🎂', he: 'יוֹם הֻלֶּדֶת',        en: 'a birthday party' },
    { id: 'dance',   emoji: '💃', he: 'רוֹקְדִים',             en: 'everybody dances' },
    { id: 'sing',    emoji: '🎤', he: 'שָׁרִים בְּיַחַד',      en: 'singing together' },
    { id: 'fly',     emoji: '🪁', he: 'עָפִים',                 en: 'learning to fly' },
    { id: 'lost',    emoji: '🧭', he: 'הָלַכְתִּי לְאִבּוּד',  en: 'getting lost and finding the way home' },
    { id: 'friend',  emoji: '🤝', he: 'חָבֵר חָדָשׁ',          en: 'making a new friend' },
    { id: 'fight',   emoji: '😠', he: 'רָבִים וּמַשְׁלִימִים', en: 'a fight and then making up' },
    { id: 'rain',    emoji: '🌧️', he: 'יוֹרֵד גֶּשֶׁם',        en: 'it starts to rain' },
    { id: 'storm',   emoji: '⛈️', he: 'סְעָרָה',                en: 'a big storm' },
    { id: 'magic',   emoji: '✨', he: 'קֶסֶם',                  en: 'a magic spell' },
    { id: 'wish',    emoji: '🌠', he: 'מִשְׁאָלָה',             en: 'making a wish' },
    { id: 'sleep',   emoji: '😴', he: 'הוֹלְכִים לִישֹׁן',     en: 'going to sleep' },
    { id: 'wake',    emoji: '⏰', he: 'מִתְעוֹרְרִים בַּבֹּקֶר', en: 'waking up in the morning' },
    { id: 'treasure',emoji: '💎', he: 'מְחַפְּשִׂים אוֹצָר',    en: 'a treasure hunt' },
    { id: 'cook',    emoji: '🎂', he: 'אוֹפִים עוּגָה',        en: 'baking a cake' },
    { id: 'pizza',   emoji: '🍕', he: 'מְכִינִים פִּיצָה',     en: 'making pizza' },
    { id: 'scared',  emoji: '👻', he: 'קְצָת מַפְחִיד',        en: 'something a little scary (but it turns out fine)' },
    { id: 'brave',   emoji: '💪', he: 'אֲנִי אַמִּיצָה',       en: 'being brave' },
    { id: 'miss',    emoji: '🥺', he: 'מִתְגַּעְגְּעִים',      en: 'missing someone' },
    { id: 'silly',   emoji: '🤪', he: 'שְׁטֻיּוֹת',            en: 'silly nonsense and jokes' },
    { id: 'trip',    emoji: '🚗', he: 'טִיּוּל',                en: 'a trip' },
    { id: 'camping', emoji: '⛺', he: 'קֶמְפִּינְג',            en: 'camping in a tent' },
    { id: 'win',     emoji: '🏆', he: 'מְנַצְּחִים',            en: 'winning a big race' },
    { id: 'lose',    emoji: '🎗️', he: 'הִפְסַדְתִּי, לֹא נוֹרָא', en: 'losing, and it is okay' },
    { id: 'school1', emoji: '🎒', he: 'יוֹם רִאשׁוֹן בְּבֵית הַסֵּפֶר', en: 'the first day of school' },
    { id: 'homework',emoji: '📚', he: 'שִׁעוּרֵי בַּיִת',      en: 'doing homework' },
    { id: 'doctor',  emoji: '🩹', he: 'הוֹלְכִים לָרוֹפֵא',    en: 'going to the doctor' },
    { id: 'tooth',   emoji: '🦷', he: 'נָפְלָה לִי שֵׁן',      en: 'losing a tooth' },
    { id: 'sick',    emoji: '🤧', he: 'חוֹלָה בַּמִּטָּה',     en: 'being sick in bed' },
    { id: 'shabbat', emoji: '🕯️', he: 'שַׁבָּת',                en: 'Shabbat' },
    { id: 'chanukah',emoji: '🕎', he: 'חֲנֻכָּה',               en: 'Chanukah' },
    { id: 'purim',   emoji: '🎭', he: 'פּוּרִים',               en: 'Purim costumes' },
    { id: 'pesach',  emoji: '🍷', he: 'פֶּסַח',                 en: 'Passover' },
    { id: 'newyear', emoji: '🍎', he: 'רֹאשׁ הַשָּׁנָה',        en: 'Rosh Hashanah' },
    { id: 'snowday', emoji: '☃️', he: 'בּוֹנִים אִישׁ שֶׁלֶג', en: 'building a snowman' },
    { id: 'swim',    emoji: '🏊', he: 'לוֹמְדִים לִשְׂחוֹת',   en: 'learning to swim' },
    { id: 'bike',    emoji: '🚲', he: 'רוֹכְבִים עַל אוֹפַנַּיִם', en: 'riding a bike' },
    { id: 'football',emoji: '⚽', he: 'מְשַׂחֲקִים כַּדּוּרֶגֶל', en: 'playing football' },
    { id: 'hide',    emoji: '🙈', he: 'מַחְבּוֹאִים',           en: 'hide and seek' },
    { id: 'picnic',  emoji: '🧺', he: 'פִּיקְנִיק',             en: 'a picnic' },
    { id: 'garden',  emoji: '🌱', he: 'שׁוֹתְלִים פֶּרַח',      en: 'planting a flower and watching it grow' },
    { id: 'pet',     emoji: '🐾', he: 'חַיַּת מַחְמָד חֲדָשָׁה', en: 'getting a new pet' },
    { id: 'rescue',  emoji: '🚒', he: 'מַצִּילִים מִישֶׁהוּ',  en: 'rescuing someone' },
    { id: 'fix',     emoji: '🔧', he: 'מְתַקְּנִים מַשֶּׁהוּ',  en: 'fixing something broken' },
    { id: 'invent',  emoji: '💡', he: 'מַמְצִיאִים הַמְצָאָה',  en: 'inventing a crazy invention' },
    { id: 'shrink',  emoji: '🔬', he: 'נִהְיֵיתִי קְטַנָּה',   en: 'shrinking to the size of an ant' },
    { id: 'giant',   emoji: '🦶', he: 'נִהְיֵיתִי עֲנָקִית',   en: 'becoming a giant' },
    { id: 'timetravel', emoji: '⏳', he: 'מַסָּע בַּזְּמַן',     en: 'time travel' },
    { id: 'talkanimals', emoji: '🗣️', he: 'מְדַבְּרִים עִם חַיּוֹת', en: 'talking to animals' },
    { id: 'gift',    emoji: '🎁', he: 'מַתָּנָה',               en: 'a surprise gift' },
    { id: 'hug',     emoji: '🤗', he: 'חִבּוּק',                en: 'a big hug' },
    { id: 'goodbye', emoji: '👋', he: 'נִפְרָדִים',             en: 'saying goodbye' },
    { id: 'love',    emoji: '❤️', he: 'אוֹהֲבִים',              en: 'love' },
    { id: 'help',    emoji: '🫶', he: 'עוֹזְרִים לְמִישֶׁהוּ',  en: 'helping someone' },
    { id: 'share',   emoji: '🍪', he: 'מִתְחַלְּקִים',          en: 'sharing' },
    { id: 'clean',   emoji: '🧹', he: 'מְסַדְּרִים אֶת הַחֶדֶר', en: 'cleaning up the room' },
    { id: 'bath',    emoji: '🛁', he: 'אַמְבַּטְיָה',           en: 'bath time with bubbles' },
    { id: 'concert', emoji: '🎸', he: 'הוֹפָעָה גְּדוֹלָה',    en: 'a big concert' },
  ],
  mood: [
    { id: 'happy',  emoji: '😄', he: 'שָׂמֵחַ',           en: 'happy' },
    { id: 'silly',  emoji: '🤣', he: 'מַצְחִיק',          en: 'funny and silly' },
    { id: 'calm',   emoji: '😌', he: 'רָגוּעַ',           en: 'calm and cozy' },
    { id: 'sad',    emoji: '😢', he: 'קְצָת עָצוּב',      en: 'a little sad' },
    { id: 'excite', emoji: '🤩', he: 'מְרַגֵּשׁ',         en: 'exciting' },
    { id: 'scary',  emoji: '😱', he: 'מַפְחִיד',          en: 'spooky (kid-friendly)' },
    { id: 'love',   emoji: '🥰', he: 'אוֹהֵב',            en: 'full of love' },
    { id: 'angry',  emoji: '😤', he: 'כּוֹעֵס',           en: 'a bit angry' },
    { id: 'sleepy', emoji: '🥱', he: 'מְנֻמְנָם',         en: 'sleepy' },
    { id: 'proud',  emoji: '😎', he: 'גֵּאָה בְּעַצְמִי', en: 'proud of myself' },
    { id: 'shy',    emoji: '😳', he: 'בַּיְשָׁנִית',      en: 'shy' },
    { id: 'curious',emoji: '🧐', he: 'סַקְרָנִית',        en: 'curious' },
    { id: 'surprised', emoji: '😲', he: 'מֻפְתַּעַת',     en: 'surprised' },
    { id: 'energetic', emoji: '⚡', he: 'מְלֵאַת אֶנֶרְגְּיָה', en: 'full of energy' },
    { id: 'dreamy', emoji: '🌙', he: 'חוֹלֶמֶת',          en: 'dreamy' },
    { id: 'magic',  emoji: '✨', he: 'קְסוּם',            en: 'magical' },
  ],
  style: [
    { id: 'kpop',    emoji: '💜', he: 'קֵיי־פּוֹפּ',        en: 'K-pop', form: 'k-pop',
      style: 'K-Pop, Idol Pop, Energetic, Glossy, Synth bass, Electronic drums, Group vocals, Female vocals, Big hook, 120 BPM' },
    { id: 'pop',     emoji: '🎤', he: 'פּוֹפּ',              en: 'pop', form: 'pop song',
      style: 'Modern Pop, Catchy, Bright, Synth-driven, Upbeat, Polished production, Female vocals' },
    { id: 'disney',  emoji: '🏰', he: 'דִּיסְנִי',           en: 'Disney musical', form: 'disney musical',
      style: 'Disney Musical, Broadway, Orchestral, Soaring strings, Piano, Magical, Emotional build, Female lead vocals, Choir finale' },
    { id: 'princess',emoji: '👑', he: 'שִׁיר נְסִיכָה',      en: 'princess ballad', form: 'ballad',
      style: 'Princess Ballad, Gentle piano, Strings, Dreamy, Sweet female vocals, Magical, Slow build' },
    { id: 'rock',    emoji: '🎸', he: 'רוֹק',                en: 'rock', form: 'rock anthem',
      style: 'Kids Rock, Electric guitars, Energetic drums, Fun, Loud, Sing-along chorus' },
    { id: 'rap',     emoji: '🧢', he: 'רַאפּ',               en: 'rap', form: 'rap / hip-hop',
      style: 'Kids Hip-Hop, Bouncy beat, Playful rap, Fun, Clean, Catchy hook' },
    { id: 'disco',   emoji: '🪩', he: 'דִּיסְקוֹ',           en: 'disco', form: 'pop song',
      style: 'Disco, Funky bass, Strings, Sparkly, Dance, Feel-good, Female vocals' },
    { id: 'edm',     emoji: '🎧', he: 'מְסִבָּה',            en: 'party / dance', form: 'pop song',
      style: 'Kids EDM, Dance, Big drop, Bright synths, Handclaps, Party, Female vocals' },
    { id: 'hasidic', emoji: '🕺', he: 'חֲסִידִי',            en: 'hasidic', form: 'hasidic',
      style: 'Hasidic Pop, Joyful, Clarinet, Strings, Uplifting, Wedding energy, Kids choir' },
    { id: 'mizrahi', emoji: '🪕', he: 'מִזְרָחִי',           en: 'mizrahi', form: 'mizrahi',
      style: 'Mizrahi Pop, Darbuka, Oud, Strings, Happy, Dance, Female vocals' },
    { id: 'lullaby', emoji: '🌙', he: 'שִׁיר עֶרֶשׂ',        en: 'lullaby', form: 'lullaby',
      style: 'Lullaby, Soft, Music box, Acoustic guitar, Gentle female vocals, Calm, Slow' },
    { id: 'kids',    emoji: '🧸', he: 'שִׁיר יְלָדִים',      en: "children's song", form: "children's song",
      style: 'Children Song, Playful, Ukulele, Bright, Simple melody, Happy, Sing-along' },
    { id: 'opera',   emoji: '🎭', he: 'אוֹפֶּרָה',           en: 'opera', form: 'opera',
      style: 'Kids Opera, Orchestral, Dramatic, Soprano, Grand, Fun' },
    { id: 'jazz',    emoji: '🎷', he: 'גֶ׳אז',               en: 'jazz', form: 'jazz',
      style: 'Playful Jazz, Swing, Piano, Upright bass, Brushed drums, Warm female vocals, Cheerful' },
    { id: 'country', emoji: '🤠', he: 'קַאנְטְרִי',          en: 'country', form: 'country',
      style: 'Kids Country, Acoustic guitar, Banjo, Clapping, Sunny, Storytelling, Female vocals' },
    { id: 'reggae',  emoji: '🌴', he: 'רֶגֵּיי',             en: 'reggae', form: 'reggae',
      style: 'Kids Reggae, Sunny, Off-beat guitar, Relaxed, Island vibe, Happy vocals' },
    { id: 'circus',  emoji: '🎪', he: 'קִרְקָס',             en: 'circus march', form: 'children\'s song',
      style: 'Circus March, Brass band, Accordion, Playful, Fast, Comical, Fun' },
    { id: 'epic',    emoji: '🐉', he: 'הַרְפַּתְקָה',        en: 'epic adventure', form: 'anthem',
      style: 'Epic Adventure, Cinematic, Orchestral, Drums, Choir, Heroic, Female lead vocals' },
  ],
};

export const card = (step, id) => (CARDS[step] || []).find(c => c.id === id) || null;

/** Vocalized sentence she can read back: "שִׁיר עַל נְסִיכָה בֶּחָלָל, יוֹם הֻלֶּדֶת, שָׂמֵחַ" */
export function sentence(pick) {
  const w = card('who', pick.who), wh = card('where', pick.where), wt = card('what', pick.what), m = card('mood', pick.mood), s = card('style', pick.style);
  const wo = card('world', pick.world);
  const parts = [];
  if (w) parts.push(w.id === 'me' ? 'שִׁיר עָלַי' : `שִׁיר עַל ${w.he}`); else parts.push('שִׁיר');
  if (wh) parts.push(wh.he);
  const tail = [];
  if (wt) tail.push(wt.he);
  if (m) tail.push(m.he);
  let out = parts.join(' ');
  if (tail.length) out += ' — ' + tail.join(', ');
  if (wo && wo.en) out += `, כְּמוֹ בְּ״${wo.he}״`;
  if (s) out += ` (${s.he})`;
  return out;
}

/** English/Hebrew brief for the Create tab on the parent side */
export function brief(idea, kidName = 'Gala') {
  const p = idea.cards || {};
  const w = card('who', p.who), wh = card('where', p.where), wt = card('what', p.what), m = card('mood', p.mood), s = card('style', p.style);
  const lines = [`A song invented by ${kidName}, a 7-year-old girl (she doesn't read English; the song is in Hebrew).`];
  const bits = [];
  if (w) bits.push(`about ${w.en}`); if (wh) bits.push(wh.en); if (wt) bits.push(`what happens: ${wt.en}`); if (m) bits.push(`mood: ${m.en}`);
  if (bits.length) lines.push('Her picture cards: ' + bits.join(' · ') + '.');
  if (s) lines.push(`Style she chose: ${s.en}.`);
  const wo = card('world', p.world);
  if (wo && wo.en) lines.push(`Inspired by the world of ${wo.en}: use that universe's characters, places and spirit as she knows them, but write an ORIGINAL song — do not copy or paraphrase existing lyrics from it.`);
  if (idea.transcript) lines.push(`In her own words (transcribed from her recording, keep her ideas, images and phrases): "${idea.transcript}"`);
  if (idea.description) lines.push(`Her drawing/photo, as described: ${idea.description}`);
  if (idea.note) lines.push(`Parent's note: ${idea.note}`);
  return lines.join('\n');
}
